development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: shainagates
  pool:     5
  email: 
  password: 
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: shainagates
  pool:     5
  email: 
  password: 
  template: template0