development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: once-and-future-prints
  pool:     5
  email: 
  password: 
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: once-and-future-prints
  pool:     5
  email: 
  password: 
  template: template0